### ISSUE TITLE
Cannot convert value of type 'CKQuery' to expected argument type 'Selector?'

### ISSUE THREAD

**Issue by m-appleseed** [PromiseKit/CloudKit#6]
Why can this error occur? 😓

<img width="1019" alt="Снимок экрана 2019-03-22 в 16 08 22" src="https://user-images.githubusercontent.com/15248225/54824867-3ac48b80-4cbd-11e9-956a-87235d8e5f56.png">

**Comment by mxcl** [comment]
PromiseKit does not provide a promise for the `perform` function.

**Comment by m-appleseed** [comment]
So what about here https://github.com/PromiseKit/CloudKit/blob/master/Sources/CKDatabase%2BPromise.swift?

![2019-03-22 16 38 27](https://user-images.githubusercontent.com/15248225/54826513-005ced80-4cc1-11e9-9484-5c175a33122f.jpg)

**Comment by mxcl** [comment]
Sorry was looking in `CKContainer.swift`.

Did you import `PromiseKit` and if necessary `PMKCloudKit`?

**Comment by m-appleseed** [comment]
> Did you import PromiseKit and if necessary PMKCloudKit?

Sure, `PromiseKit` imported. I have a project in Swift. So should I import `PMKFoundation` or `PMKCloudKit`?

In README written about `PMKFoundation`:
<img width="250" alt="Снимок экрана 2019-03-22 в 17 05 06" src="https://user-images.githubusercontent.com/15248225/54828180-afe78f00-4cc4-11e9-95bc-0d64d8f96416.png">

I installed `PromiseKit/CloudKit` and `PromiseKit/Foundation` via Cocoa Pods:
``` 
pod 'PromiseKit'
pod 'PromiseKit/CloudKit', '~> 6.0'
pod 'PromiseKit/Foundation', '~> 6.0'
```
But I can't import it:

<img width="494" alt="Снимок экрана 2019-03-22 в 17 13 46" src="https://user-images.githubusercontent.com/15248225/54828896-42d4f900-4cc6-11e9-8d85-55ac901d96ad.png">

**Comment by mxcl** [comment]
Try specifying the return type in firstly. See our TroubleShooting guide for more tips

**Comment by m-appleseed** [comment]
Sorry, I had a mistake. Question solved 👍
